//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingStoredProcedureMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ABC_Company_DBEntities : DbContext
    {
        public ABC_Company_DBEntities()
            : base("name=ABC_Company_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<getAllDetails_Result> getAllDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllDetails_Result>("getAllDetails");
        }
    
        public virtual int FN_getAllDetails1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FN_getAllDetails1");
        }
    }
}
